"""
Unit tests for AuditGuard CLI commands:
- import-scope: StateHunter YAML ingestion and config merging
- endpoints: Discovered endpoint auditing
- export-report: Vulnerability markdown report generation
"""

import io
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import yaml
from core.scope_validator import ScopeValidator, OutOfScopePathError
from main import cmd_import_scope, cmd_endpoints, cmd_export_report, cmd_check, cmd_scope


class MockArgs:
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)


SAMPLE_STATEHUNTER_EXPORT = """# AuditGuard Scope Definition generated by StateHunter
# Target: https://lab.target.internal/
# Generated: 2026-09-11T12:00:00.000Z
#
# --- Vulnerability Disclosure Policy (RFC 9116) ---
# Policy URL: https://target.internal/vdp-policy
# Contact: security@target.internal

programs:
  statehunter_imported_lab:
    name: "Synthetic Lab Target"
    in_scope:
      - "https://lab.target.internal"
      - "*.lab.target.internal"
    excluded_paths:
      - "/logout"
      - "/delete"
      - "/billing"
      - "*/admin/staging/*"
    discovered_endpoints:
      - "/dashboard"
      - "/api/v1/metrics"
      - "/billing/invoices"
      - "/api/v1/billing/stripe-webhook"
      - "/admin/secret-console"
    flagged_sensitive_endpoints:
      - "/admin/secret-console"
      - "/billing/invoices"
    robots_disallow_directives:
      - "/private-crawler-trap"
"""


class TestCliCommands(unittest.TestCase):

    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.config_dir = Path(self.temp_dir.name) / "config"
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self.config_file = self.config_dir / "programs.yaml"

        initial_cfg = {
            "active_program": "base_test",
            "programs": {
                "base_test": {
                    "name": "Base Test",
                    "in_scope": ["https://base.org"],
                    "out_of_scope": {"paths": ["/logout"]},
                }
            },
        }
        with open(self.config_file, "w", encoding="utf-8") as f:
            yaml.dump(initial_cfg, f)

        # Audit directory
        self.audit_dir = Path(self.temp_dir.name) / "audit"
        self.audit_dir.mkdir(parents=True, exist_ok=True)
        self.audit_file = self.audit_dir / "audit_log.jsonl"

        mock_audit_entry = {
            "request_id": "test_req_12345",
            "timestamp": "2026-09-11T12:00:00Z",
            "program": "Base Test",
            "request": {
                "method": "POST",
                "url": "https://base.org/api/sensitive-leak",
                "headers": {"User-Agent": "AuditGuard", "X-Bug-Bounty": "Tester"},
                "body_preview": '{"action": "dump_users"}',
            },
            "response": {
                "status_code": 200,
                "headers": {"content-type": "application/json"},
                "body_preview": '{"users": ["admin@base.org", "root@base.org"]}',
                "elapsed_ms": 42.5,
            },
            "rationale": "Testing unauthorized user dump",
        }
        with open(self.audit_file, "w", encoding="utf-8") as f:
            f.write(json.dumps(mock_audit_entry) + "\n")

    def tearDown(self):
        self.temp_dir.cleanup()

    def test_import_scope_from_file_and_activate(self):
        export_path = Path(self.temp_dir.name) / "statehunter_export.yaml"
        export_path.write_text(SAMPLE_STATEHUNTER_EXPORT, encoding="utf-8")

        args = MockArgs(file=str(export_path), activate=True)

        with patch("main.Path") as mock_path:
            def path_side_effect(arg):
                if str(arg) == "config/programs.yaml":
                    return self.config_file
                return Path(arg)
            mock_path.side_effect = path_side_effect

            with patch("sys.stdout", new_callable=io.StringIO) as mock_stdout:
                cmd_import_scope(args)
                output = mock_stdout.getvalue()

        self.assertIn("Successfully Imported Program: 'Synthetic Lab Target'", output)
        self.assertIn("Active program set to: 'statehunter_imported_lab'", output)

        with open(self.config_file, "r", encoding="utf-8") as f:
            saved_cfg = yaml.safe_load(f)

        self.assertEqual(saved_cfg["active_program"], "statehunter_imported_lab")
        imported_prog = saved_cfg["programs"]["statehunter_imported_lab"]
        self.assertEqual(imported_prog["policy_url"], "https://target.internal/vdp-policy")
        self.assertEqual(imported_prog["contact"], "security@target.internal")
        self.assertIn("https://lab.target.internal", imported_prog["in_scope"])
        self.assertIn("/billing", imported_prog["excluded_paths"])
        self.assertIn("/dashboard", imported_prog["discovered_endpoints"])

    def test_endpoints_command_evaluates_scope(self):
        prog = {
            "name": "Endpoint Audit Lab",
            "in_scope": ["https://lab.target.internal"],
            "excluded_paths": ["/billing", "*/admin/*"],
            "discovered_endpoints": [
                "/dashboard",
                "/billing/invoices",
                "/admin/metrics",
            ],
            "flagged_sensitive_endpoints": ["/admin/metrics"],
        }
        val = ScopeValidator(prog)

        args = MockArgs(flagged_only=False)
        with patch("main.load_config") as mock_cfg, patch("main.get_active_validator") as mock_val:
            mock_cfg.return_value = {"active_program": "lab"}
            mock_val.return_value = ("lab", val, prog)

            with patch("sys.stdout", new_callable=io.StringIO) as mock_stdout:
                cmd_endpoints(args)
                output = mock_stdout.getvalue()

        self.assertIn("/dashboard", output)
        self.assertIn("[BLOCKED (Excluded)]", output)
        self.assertIn("/billing/invoices", output)
        self.assertIn("/admin/metrics", output)

    def test_export_report_from_audit_entry(self):
        out_report_path = Path(self.temp_dir.name) / "test_report.md"
        args = MockArgs(
            request_id="test_req_12345",
            title="User Data Leak via Unauthenticated Endpoint",
            severity="High",
            cwe="CWE-200",
            summary="Endpoint leaks administrator user accounts without authentication.",
            steps=None,
            impact="Exposure of corporate PII and administrative credentials.",
            remediation="Enforce OAuth2 Bearer token checks.",
            reporter="TestResearcher",
            output=str(out_report_path),
        )

        with patch("main.AuditLogger") as mock_logger_cls:
            from audit.audit_logger import AuditLogger
            real_logger = AuditLogger(str(self.audit_file))
            mock_logger_cls.return_value = real_logger

            with patch("sys.stdout", new_callable=io.StringIO) as mock_stdout:
                cmd_export_report(args)
                output = mock_stdout.getvalue()

        self.assertIn("report exported successfully", output)
        self.assertTrue(out_report_path.exists())
        content = out_report_path.read_text(encoding="utf-8")
        self.assertIn("# User Data Leak via Unauthenticated Endpoint", content)
        self.assertIn("**Severity:** HIGH", content)
        self.assertIn("**Weakness:** CWE-200", content)
        self.assertIn("curl -i -X POST", content)
        self.assertIn("https://base.org/api/sensitive-leak", content)
        self.assertIn("admin@base.org", content)


if __name__ == "__main__":
    unittest.main()
